### Teste para a raiz da API
GET http://localhost:5273

### Listar produtos
GET http://localhost:5273/api/produto/listar


### Buscar produto
GET http://localhost:5273/api/produto/buscar/b4cb1b32-8139-49c2-8182-47f0f8a91044

### Cadastrar produto
POST http://localhost:5273/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Mouse",
    "preco" : 7.5
}