### Teste para a raiz da API
GET http://localhost:5273

### Listar produtos
GET http://localhost:5273/api/produto/listar

### Cadastrar produto
POST http://localhost:5273/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Mouse"
}
